<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE audit [<!ELEMENT audit (profile+ , date , conversion_factor , conversion_factor_unit)><!ELEMENT profile (description , values)><!ELEMENT description (#PCDATA)><!ELEMENT values (type , quantity , kWhPerYear , standby_factor , unit , perUnit , source , source_date)><!ELEMENT type (#PCDATA)><!ELEMENT quantity (#PCDATA)><!ELEMENT kWhPerYear (#PCDATA)><!ELEMENT standby_factor (#PCDATA)><!ELEMENT unit (#PCDATA)><!ELEMENT perUnit (#PCDATA)><!ELEMENT source (#PCDATA)><!ELEMENT source_date (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT conversion_factor (#PCDATA)><!ELEMENT conversion_factor_unit (#PCDATA)>]><audit>
  <profile>
    <description>Personal Computers, Desktop</description>
    <values role="Shared PC" location="C27" weeksOnPerYear="52" daysOnPerWeek="5" onPerDay="5" offPerDay="19" standbyPerDay="0">
      <type>Computing equipment</type>
      <quantity>51</quantity>
      <kWhPerYear>334.55772274778</kWhPerYear>
      <standby_factor>1</standby_factor>
      <unit>kg</unit>
      <perUnit>year</perUnit>
      <source>MTP/defra/amee 2008</source>
      <source_date>2011-02-16 07:55:18.0</source_date>
    </values>
  </profile>
  <profile>
    <description>Printer, Laser</description>
    <values role="Shared Printer" location="C27" weeksOnPerYear="52" daysOnPerWeek="7" onPerDay="1" offPerDay="0" standbyPerDay="23">
      <type>Computing equipment</type>
      <quantity>1</quantity>
      <kWhPerYear>214.86425902864</kWhPerYear>
      <standby_factor>1</standby_factor>
      <unit>kg</unit>
      <perUnit>year</perUnit>
      <source>MTP/defra/amee 2008</source>
      <source_date>2007-07-27 09:47:59.0</source_date>
    </values>
  </profile>
  <profile>
    <description>Personal Computers, Desktop no monitor</description>
    <values role="Server" location="C27" weeksOnPerYear="52" daysOnPerWeek="7" onPerDay="24" offPerDay="0" standbyPerDay="0">
      <type>Computing equipment</type>
      <quantity>10</quantity>
      <kWhPerYear>856.84373228012</kWhPerYear>
      <standby_factor>1</standby_factor>
      <unit>kg</unit>
      <perUnit>year</perUnit>
      <source>dgen / defra 2007</source>
      <source_date>2008-11-26 15:46:08.0</source_date>
    </values>
  </profile>
  <date>Thu Nov 03 2011 18:26:36 GMT+0000 (GMT)</date>
  <conversion_factor>0.54522</conversion_factor>
  <conversion_factor_unit>Kg CO2e</conversion_factor_unit>
</audit>
