<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE audit [<!ELEMENT audit (profile+ , date , conversion_factor , conversion_factor_unit)><!ELEMENT profile (description , values)><!ELEMENT description (#PCDATA)><!ELEMENT values (type , quantity , role, location, kWhPerYear , weeksOnPerYear, daysOnPerWeek, onPerDay , offPerDay, standbyPerDay , standby_factor , unit , perUnit , source , source_date)><!ELEMENT type (#PCDATA)><!ELEMENT quantity (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT location (#PCDATA)><!ELEMENT kWhPerYear (#PCDATA)><!ELEMENT weeksOnPerYear (#PCDATA)><!ELEMENT daysOnPerWeek (#PCDATA)><!ELEMENT onPerDay (#PCDATA)><!ELEMENT offPerDay (#PCDATA)><!ELEMENT standbyPerDay (#PCDATA)><!ELEMENT standby_factor (#PCDATA)><!ELEMENT unit (#PCDATA)><!ELEMENT perUnit (#PCDATA)><!ELEMENT source (#PCDATA)><!ELEMENT source_date (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT conversion_factor (#PCDATA)><!ELEMENT conversion_factor_unit (#PCDATA)>]><audit>
  <profile>
    <description>Personal Computers, Desktop 1 monitor</description>
    <values>
      <type>Computing equipment</type>
      <quantity>1</quantity>
      <kWhPerYear>223.62679825992</kWhPerYear>
      <standby_factor>1</standby_factor>
      <role>Desktop PC</role>
      <location>C68</location>
      <weeksOnPerYear>48</weeksOnPerYear>
      <daysOnPerWeek>5</daysOnPerWeek>
      <onPerDay>7</onPerDay>
      <offPerDay>13</offPerDay>
      <standbyPerDay>4</standbyPerDay>
      <unit>kg</unit>
      <perUnit>year</perUnit>
      <source>dgen / defra 2007</source>
      <source_date>2008-11-26 15:46:08.0</source_date>
    </values>
  </profile>
  <profile>
    <description>Monitor, LCD</description>
    <values>
      <type>Computing equipment</type>
      <quantity>1</quantity>
      <kWhPerYear>81.86899128269</kWhPerYear>
      <standby_factor>1</standby_factor>
      <role>Other</role>
      <location>C68</location>
      <weeksOnPerYear>48</weeksOnPerYear>
      <daysOnPerWeek>5</daysOnPerWeek>
      <onPerDay>5</onPerDay>
      <offPerDay>0</offPerDay>
      <standbyPerDay>19</standbyPerDay>
      <unit>kg</unit>
      <perUnit>year</perUnit>
      <source>dgen / defra 2007</source>
      <source_date>2008-11-26 15:46:11.0</source_date>
    </values>
  </profile>
  <date>Sat Nov 19 2011 14:36:50 GMT+0000 (GMT)</date>
  <conversion_factor>0.59368</conversion_factor>
  <conversion_factor_unit>Kg CO2e</conversion_factor_unit>
</audit>
