<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE audit [<!ELEMENT audit (profile+ , date , conversion_factor , conversion_factor_unit)><!ELEMENT profile (description , values)><!ELEMENT description (#PCDATA)><!ELEMENT values (type , quantity , kWhPerYear , standby_factor , unit , perUnit , source , source_date)><!ELEMENT type (#PCDATA)><!ELEMENT quantity (#PCDATA)><!ELEMENT kWhPerYear (#PCDATA)><!ELEMENT standby_factor (#PCDATA)><!ELEMENT unit (#PCDATA)><!ELEMENT perUnit (#PCDATA)><!ELEMENT source (#PCDATA)><!ELEMENT source_date (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT conversion_factor (#PCDATA)><!ELEMENT conversion_factor_unit (#PCDATA)>]><audit>
  <profile>
    <description>Fujitsu CELSIUS M470 POWER E-STAR5</description>
    <values>
      <type>Workstation</type>
      <quantity>1</quantity>
      <kWhPerYear>113.07</kWhPerYear>
      <standby_factor>0.95</standby_factor>
      <unit>kg</unit>
      <perUnit>year</perUnit>
      <source>www.energystar.gov</source>
      <source_date>2009-09-02 16:53:08.0</source_date>
    </values>
  </profile>
  <date>Fri Oct 28 19:31:46 UTC+0100 2011</date>
  <conversion_factor>0.59368</conversion_factor>
  <conversion_factor_unit>Kg CO2e</conversion_factor_unit>
</audit>
